name:                template
version:             0.1.0.0
author:              "tlarrieu"

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -O2

library:
  source-dirs: src

executables:
  template-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - template
