name:                day14
version:             0.1.0.0
author:              "tlarrieu"

dependencies:
- base >= 4.7 && < 5
- containers
- split

ghc-options:
  - -Wall
  - -O2

library:
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - day14
      - hspec

executables:
  day14-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day14
