name:                day11
version:             0.1.0.0
author:              "tlarrieu"

dependencies:
- base >= 4.7 && < 5
- split
- containers

ghc-options:
  - -Wall
  - -O2

library:
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - day11
      - hspec

executables:
  day11-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day11
